### PR TITLE
feat(SlateAdmin): clearer contact/guardian management

### PR DESCRIPTION
**Pull request by themightychris**
This PR explores removing the ambiguity around guardianship designation and forward/inverse relationships

Screen Shot 2021-10-11 at 4 52 33 PM

A rough form of the layout and how the editing would work is functioning here, but only deletes persist to the server currently. @ryon will definitely need to take a pass at this before it goes out.

@tgaffey @holly-g @ryon looking for any feedback on how this looks and how well it makes the two labels and guardian directionality more obvious

### CODE REVIEW

**Comment by ryon** [comment]
This makes sense but it's pretty noisy, with a lot of repeated elements.

Also, Is it important to show the inverse relationship? Is that ever ambiguous?

I can work on refining this idea a bit.

**Comment by themightychris** [comment]
@ryon I think it _is_ important to show both together. When creating or editing a relationship you want to set/edit them as a unit. It would be confusing to do the two halves from separate contexts and probably lead to a lot of incomplete data

Verbosity and explicitness is very important here because this is inherently complex data that leads to who a child's most personal information gets sent to

Further, it needs to be viewable and editable from both ends of the connection

**Comment by ryon** [comment]
@themightychris Are these inverse relationships always set explicitly? When you select "Coach" does it not pick "Coachee" for you? Are there cases in which a Coach's inverse would not be Coachee?

**Comment by themightychris** [comment]
@ryon there's a set of "templates" that will be suggested as you type in the first field, if you select one it may prefill the inverse and some properties of the related person if we're creating a new one on the fly. Both labels can be set arbitrarily though and if you type a custom one into the first field there will be no prefill for the second. The version in this branch doesn't have any of those smarts hooked up, play with the `develop` version on the latest.slate-cbl site or locally

**Comment by themightychris** [comment]
"coach" is one that's not in the templates that I've seen a lot in practice, was thinking we should add it actually

**Comment by themightychris** [comment]
I think it is important that people's chosen labels can be put in when they vary from the common ones, school staff need the ability to respect people's preferences when communicating with the home. Sometimes it's important for formal relationships within the school too

**Comment by themightychris** [comment]
Discussion points from today's workshop:

- No one knows what the shield means, we should rely on it less somehow (maybe entirely separate list of guardians from list of contacts, maybe always show guardian/non-guardian text so the icon is secondary)
- We could use some help text here noting what guardianship means: maybe embedded within a modal and maybe embedded as a banner at the top of the list
- Maybe we need to do some mockups of different options (figma or static)
- Maybe we can remove the word "inverse"

**Comment by ryon** [comment]
Latest UI treatment:

Screen Shot 2021-11-23 at 3 40 39 PM

Adding/removing guardian status will be available as a checkbox with an explicit label in a small popover form that appears when you click to edit the relationship label, on either side. It will also be available to set when you first define a relationship.

**Pull request merged**
