### PR TITLE
Cc overrides

### PR DESCRIPTION
**Pull request by aharley40**
@themightychris Beeber and CC have the same files references in the following commit, https://github.com/SlateFoundation/slate/commit/1015fa88565401d0e938d69e659dc672fc3c25af. 

We can delete all the local files once this is pulled into development.

### CODE REVIEW

**Comment by themightychris** [comment]
@aharley40 the narratives/standards classes need to be put in https://github.com/SlateFoundation/scienceleadership-sbg instead, and possibly have their name spaces changed (this will be something to consider in their import script too)

Interims should stay in slate core I think

**Comment by themightychris** [comment]
@aharley40 

- [ ] the Tag/TagItem changes need to be PR'd into emergence-skeleton instead

**Comment by aharley40** [comment]
@themightychris Should I or Should I not leave interims in Progress? I'm not sure why it'd get left out the new namespace for these records.

**Comment by themightychris** [comment]
Interims should stay in the Progress namespace within the main slate
repository

Standards and Narratives will need to some be architectured to "plug-in" to
progress as bonus progress types that get loaded from the
scienceleadership-sbg repository

On Thu, Sep 17, 2015 at 2:44 PM, aharley40 <notifications@github.com> wrote:

> @themightychris <https://github.com/themightychris> Should I or Should I
> not leave interims in Progress? I'm not sure why it'd get left out the new
> namespace for these records.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SlateFoundation/slate/pull/51#issuecomment-141183976>.
>



-- 
Chris Alfano
Chief Developer
Jarv.us Innovations <http://jarv.us>

(e) chris@jarv.us (m) 267-918-6166

**Pull request closed without merging**
